print("diga sua idade em anos, meses e dias e direi o total de dias")
print("quantos anos você tem?", )
anos=int(input())
print('quantos meses se passaram desde seu aniversário?')
meses=int(input())
print('e quantos dias, além do total de meses?')
dias=int(input())
print(meses*30+dias+anos*365)